# permissions for end users to view apps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: app-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kai
    app.kubernetes.io/part-of: kai
    app.kubernetes.io/managed-by: kustomize
  name: app-viewer-role
rules:
- apiGroups:
  - core.kai.io
  resources:
  - apps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kai.io
  resources:
  - apps/status
  verbs:
  - get
