apiVersion: ai.kai.io/v1alpha1
kind: ModelRuntime
metadata:
  labels:
    app.kubernetes.io/name: modelruntime
    app.kubernetes.io/instance: modelruntime-sample
    app.kubernetes.io/part-of: kai
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kai
  name: modelruntime-sample
spec:
  # TODO(user): Add fields here
